---
apiVersion: v1
kind: Service
metadata:
  name: samplecluster
  labels:
    app: samplecluster
spec:
  type: LoadBalancer
  selector:
    app: samplecluster
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP