---
apiVersion: v1
kind: Service
metadata:
  name: capstoneservice
  labels:
    app: CAPSTONE
spec:
  type: LoadBalancer
  selector:
    app: CAPSTONE
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP