apiVersion: apps/v1
kind: Deployment
metadata:
  name: samplecluster
  labels:
    app: samplecluster
  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: samplecluster
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: samplecluster
    spec:
      containers:
        - image: rajkumar080/my-app:latest
          imagePullPolicy: Always
          name: samplecluster
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"