apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstonedevops
  labels:
    app: CAPSTONE
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: CAPSTONE
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: CAPSTONE
    spec:
      containers:
        - image: rajkumar080/capstondockerapp2022
          imagePullPolicy: Always
          name: capstondockerapp2022
          ports:
            - containerPort: 80
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 1
            httpGet:
              path: /
              port: 80