apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-devpos-cluster
  labels:
    app: CAPSTONE
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: CAPSTONE
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: CAPSTONE
    spec:
      containers:
        - image: rajkumar080/devops-capstone-app:latest
          imagePullPolicy: Always
          name: capstonedevops
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 1
            httpGet:
              path: /
              port: 80
---

apiVersion: v1
kind: Service
metadata:
  name: capstoneservice
  labels:
    app: CAPSTONE
spec:
  type: LoadBalancer
  selector:
    app: CAPSTONE
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP